CREATE TABLE LANZAMIENTO_PIEZAS (

    ID NUMBER GENERATED ALWAYS AS IDENTITY,

    PIEZA1 NUMBER(1),
    PIEZA2 NUMBER(1),
    PIEZA3 NUMBER(1),
    PIEZA4 NUMBER(1),
    PIEZA5 NUMBER(1),
    PIEZA6 NUMBER(1),

    CARAS_A NUMBER(2),
    CARAS_B NUMBER(2),

    PROBABILIDAD NUMBER(8,4),

    FECHA_REGISTRO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_LANZAMIENTO
    PRIMARY KEY(ID)
);

COMMIT;